### ISSUE TITLE
Release WM ext 1.0.0-alpha

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#104]
### Outcomes

In scope for **1.0.0-alpha**: 
Website visitors: 
- Have a new or additional way to pay for stuff on the Web.
- Are able to install the WM ext to be able to pay using WM.
- Can define a maximum WM budget available monthly.
- Decide how much to pay per hour, when paying continually.
- Can decide who to pay online, using the WM ext.

Features for **1.0.0-alpha**:
1. Overall WM config:
- [x] Global enable/disable WM. See ticket [#61](https://github.com/interledger/web-monetization-extension/issues/61)  in May 2024, the decision was made to eliminate the global en/disable functionality in ticket [#256](https://github.com/interledger/web-monetization-extension/issues/256)
- [x] Enter & connect wallet address. See ticket #46 
- [x] Disconnect wallet address. See ticket #108
- [x] Generate public-private key pair to authenticate a WM user agent to the payer’s wallet. See ticket #92 
- [x] Display the public key generated by the extension during installation. See ticket #105 
- [x] Visual indication when payments are actively streaming. See ticket [#79](https://github.com/interledger/web-monetization-extension/issues/79)

2. Configure WM payments:
- [x] Set budget & renewal frequency (options being once-off or monthly). See ticket #46 
- [x] The denomination of balance is automatically inferred from the wallet address. See ticket #109 

3. Once config. is completed, users can:
- [x] Enable/disable streaming/continuous payments. See ticket #238 
- [x] For continuous payments, define a custom global hourly rate to spend on WMized websites. See ticket #60 
- [x] Website visitors can make a once-off payment (e.g. a tip). See ticket #62 

Out of scope for **1.0.0-alpha** but in scope for **1.0.0-beta**:
1. View remaining budget balance. See ticket #272 

2. Website owners, publishers or developers can make: 
2.1 Make it easier for websites to respond to receiving WM payments.
2.2 Have light tools (i.e. code snippets & libs) to add a tipping button & WM banner advert to websites.

**Comment by tselit** [comment]
Closed by ticket #215
