### ISSUE TITLE
[NEW FEATURE] Requirements - Exceptions List - add a site-specific rate of pay

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#146]
### Context

As a WM extension user, I want to configure site-specific hourly rates such that I can have a different rate of pay for each website.

### Describe the solution you would like

A way for users to configure and maintain a list of site-specific hourly rates of pay, in the context of continuous payments, where the minimum hourly rate can be 0, and the maximum 1.

### Additional context

Some things to consider: 
- config hierarchy such that config for a path to a specific resource within a domain supercedes config for the domain (e.g. config for `www.furryfriends.org/bobtail` supercedes config for `www.furryfriends.org`)
- users may want to perform bulk actions to multiple websites at the same time

### Todos

- [ ] Add debounce for the rate of pay slider;
- [ ] After changing the rate of pay, send the updated amount to the background script, convert the amount to the asset scale of the wallet (represented as a string, eg: asset code USD, asset scale 2, amount 0.01 -> `amount * 10 ** scale`) and add the website in the exception list using the below format;
- [ ] If the website is already in the exception list, only update the amount (after converting it as well);

#### Format
```json
{
  "exceptionList": {
    "https://example.com": {
      "amount": "60", 
      "interval": "3600000" // in ms
    }
  }
}
```
The `interval` property is for future proofing. For now, we will only store the default value for the interval, 1 hour in milliseconds.
