### ISSUE TITLE
Error handling/messages improvements

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#147]
### Context

The extension UI error handling can be improved by displaying more meaningful error messages to the user.

### Todos

- [x] Audit popup for better error messages
- [x] Audit background response the popup for better error messages
- [x] ~What to display when a grant is out of funds~ https://github.com/interledger/web-monetization-extension/issues/144

**Comment by sidvishnoi** [comment]
Most likely also blocked by https://github.com/interledger/open-payments/issues/482.

**Comment by sidvishnoi** [comment]
Looks much better now. Address through multiple PRs.
