### ISSUE TITLE
Support recurring monthly amount

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#148]
### Context

When connecting their wallet, users can opt-in for a recurring monthly amount.

### Todos

- [ ] When receiving the `CONNECT_WALLET` message (from popup to background) verify if the `recurring` property is `true`:
  - [ ] if `true`: generate a monthly repeating interval having the current date as a start date ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601));
  - [ ] if `false` do not generate the interval - meaning that the user opted in for a one time amount;
- [ ] Make sure to specify the interval when requesting the outgoing payment grant (https://openpayments.guide/apis/auth-server/operations/post-request/#request-body);

**Comment by tselit** [comment]
Aiming to have this ready for review by the end of this week, 19 Apr.

**Comment by tselit** [comment]
On track to go into review tomorrow, Fri, 19 Apr.
