### ISSUE TITLE
[META] Setup page improvements

### ISSUE THREAD

**Issue by sidvishnoi** [interledger/web-monetization-extension#613]
- [x] #614
   - [x] Make copy updates and validation improvements based on https://github.com/interledger/web-monetization-extension/issues/565
   - [x] Support fallback for copy-paste key when automatic copying key fails
- [x] Add service to automatically copy public key to the wallet  / along with E2E tests for each ([related](https://github.com/interledger/web-monetization-extension/issues/311))
   - [x] #615
   - [x] #616
   - [x] #617
- [x] #625
- [x] #622

Out of scope for this story:
- #618 (depends on GateHub fixing some things)
- #646
- #653
