### ISSUE TITLE
Generate key pair when the extension is installed

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#92]
### Context
A WM user wants to: 
- connect their wallet address (i.e. the sending wallet) to the WM extension, and 
- make a maximum budget of **X** amount available from the user's wallet for the WM ext. for 1 month (for v1). 

**Trust**: To authenticate messages received by a user's wallet from the WM ext, trust is established using public-key cryptography:
- At installation, the WM ext automatically generates a public-private key pair, and displays the public key on the WM ext UI.
- A user must manually load the WM extension's generated public key into their wallet **before** returning to the WM ext UI to connect the user's wallet address.
- The WM ext uses its private key to sign all messages to the user's wallet. This allows the user's wallet to authenticate that these messages are indeed from the WM ext.

**Summary**: When a user installs the WM browser extension, a public-private key pair automatically get generated & stored by the extension. When connecting their wallet, the users will be provided a public key which they will need to add in their wallet provider UI. The key pair is generated when the extension is installed.

### Todos

- [x] Use `@noble/ed25519` to generate keys
- [x] Save the private key, public key and key id in extension storage
- [x] The public key needs to be stored as a base64 encoded JWK
